import type { MealRecipe, MealTheme } from "./meal-types";

export const defaultMealThemes: MealTheme[] = [
  { id: "meal-tims-belt", title: "Tims 训练启动日", subtitle: "Bagel B.E.L.T.＋水果＋少糖 iced coffee", mealSlots: ["早餐"], source: "Tim Hortons", tags: ["训练日", "省时间", "高蛋白"], proteinHint: "约 24g；若当早午饭再加酸奶或鸡蛋", recipeId: "recipe-tims-belt", prepNote: "前一晚确认家里有香蕉或苹果", notes: "钠较高且含 bacon，一周 1–2 次即可。", accent: "coral", active: true },
  { id: "meal-yogurt-oats", title: "Nations 酸奶燕麦日", subtitle: "Greek yogurt＋燕麦＋水果＋坚果", mealSlots: ["早餐", "加餐"], source: "Nations", tags: ["免开火", "高纤维", "可隔夜"], proteinHint: "约 20–25g", recipeId: "recipe-yogurt-oats", prepNote: "周日分装燕麦和坚果；可前晚做 overnight oats", notes: "蜂蜜、granola 和花生酱不需要同时大量加入。", accent: "lime", active: true },
  { id: "meal-chinese-breakfast", title: "中式温热早餐日", subtitle: "鸡蛋＋无糖豆奶＋红薯/玉米＋水果", mealSlots: ["早餐"], source: "在家", tags: ["温热", "少加工", "可备菜"], proteinHint: "约 20g", recipeId: "recipe-chinese-breakfast", prepNote: "一次煮 6–8 个鸡蛋；红薯或玉米提前蒸熟", notes: "不要同时叠加油条、甜面包和 Timbits。", accent: "lavender", active: true },
  { id: "meal-tims-protein", title: "Tims 轻量高蛋白日", subtitle: "Egg & Cheese Muffin＋水果＋Protein Latte", mealSlots: ["早餐"], source: "Tim Hortons", tags: ["外带", "轻量", "高蛋白"], proteinHint: "三明治约 13g；Protein Latte 另补蛋白质", recipeId: "recipe-tims-protein", prepNote: "从 Nations 带一份完整水果", notes: "不点 Protein Latte 时，换普通少糖咖啡并加 Greek yogurt。", accent: "blue", active: true },
  { id: "meal-pb-toast", title: "全麦花生酱日", subtitle: "全麦面包＋花生酱＋Greek yogurt＋香蕉", mealSlots: ["早餐", "加餐"], source: "在家", tags: ["快手", "无需做饭"], proteinHint: "约 20–25g", recipeId: "recipe-pb-toast", prepNote: "无需集中备菜", notes: "花生酱 1–2 汤匙即可；用整个 Bagel 时减少其他份量。", accent: "lime", active: true },
  { id: "meal-strength-brunch", title: "力量训练早午饭", subtitle: "鸡蛋＋全麦 Bagel＋蔬菜＋水果", mealSlots: ["早餐", "午餐"], source: "在家", tags: ["训练日", "早午饭", "完整一餐"], proteinHint: "约 25–35g", recipeId: "recipe-strength-brunch", prepNote: "提前洗好番茄、黄瓜或菠菜", notes: "适合训练前 2–3 小时，或训练后作为早午饭。", accent: "coral", active: true },
  { id: "meal-treat-breakfast", title: "有边界的甜点早餐", subtitle: "酸奶/鸡蛋＋水果＋1–2 个 Timbits＋咖啡", mealSlots: ["早餐"], source: "灵活", tags: ["周末", "甜点", "不内疚"], proteinHint: "先保证酸奶或鸡蛋", recipeId: "recipe-treat-breakfast", prepNote: "不需要备菜", notes: "先吃蛋白质和水果，再吃 Timbits；甜点是配角。", accent: "lavender", active: true },
  { id: "meal-nations-plate", title: "Nations 一盘式正餐", subtitle: "一个蛋白质＋一个主食＋两种蔬菜", mealSlots: ["午餐", "晚餐"], source: "Nations", tags: ["外食", "自由搭配", "蔬菜"], proteinHint: "目标 25–35g", recipeId: "recipe-nations-plate", prepNote: "无需备菜；到店按餐盘结构选", notes: "烧腊可以吃，但少淋汁，不作为每天默认。", accent: "blue", active: true },
  { id: "meal-chicken-rice", title: "鸡肉双蔬饭", subtitle: "米饭＋鸡肉＋西兰花＋绿叶菜", mealSlots: ["午餐", "晚餐"], source: "在家", tags: ["批量备餐", "高蛋白", "训练日"], proteinHint: "约 30–35g", recipeId: "recipe-chicken-rice", prepNote: "周日烤/煎 3–4 份鸡肉，洗切蔬菜，米饭按需现煮或分装", notes: "酱汁分开放，避免整周味道过重。", accent: "lime", active: true },
  { id: "meal-beef-noodles", title: "牛肉蔬菜面", subtitle: "牛肉＋面条＋鸡蛋＋两种蔬菜", mealSlots: ["午餐", "晚餐"], source: "在家", tags: ["温热", "一锅完成"], proteinHint: "约 30g", recipeId: "recipe-beef-noodles", prepNote: "牛肉分份；青菜提前洗好但保持干燥", notes: "不要同时加超大份面、甜饮和甜点。", accent: "coral", active: true },
  { id: "meal-salmon", title: "三文鱼完整餐", subtitle: "三文鱼＋米饭/土豆＋沙拉", mealSlots: ["午餐", "晚餐"], source: "在家", tags: ["鱼类", "Omega-3", "周末"], proteinHint: "约 25–35g", recipeId: "recipe-salmon", prepNote: "冷冻鱼提前一晚移到冷藏；沙拉菜洗净沥干", notes: "一周安排 1–2 次鱼即可。", accent: "blue", active: true },
  { id: "meal-tofu", title: "豆腐炒蔬菜饭", subtitle: "豆腐＋彩色蔬菜＋米饭", mealSlots: ["午餐", "晚餐"], source: "在家", tags: ["豆制品", "蔬菜", "快炒"], proteinHint: "约 20–30g", recipeId: "recipe-tofu", prepNote: "豆腐沥水；蔬菜周日洗切分盒", notes: "可以加毛豆或鸡蛋补足蛋白质。", accent: "lavender", active: true },
  { id: "meal-tomato-egg", title: "番茄炒蛋套餐", subtitle: "番茄炒蛋＋米饭＋一份绿叶菜", mealSlots: ["午餐", "晚餐"], source: "在家", tags: ["家常", "快手", "温热"], proteinHint: "约 20–25g", recipeId: "recipe-tomato-egg", prepNote: "绿叶菜洗好；鸡蛋无需提前处理", notes: "如果当天其余两餐蛋白质偏少，可增加鸡蛋或豆腐。", accent: "coral", active: true },
  { id: "meal-hotpot", title: "清爽火锅日", subtitle: "肉/鱼/豆腐＋大量蔬菜＋适量主食", mealSlots: ["晚餐"], source: "在家", tags: ["社交", "周末", "自由搭配"], proteinHint: "按一掌到一掌半", recipeId: "recipe-hotpot", prepNote: "周日不必备；当天洗切即可", notes: "少喝汤，主食适量，不用因为火锅跳过白天正餐。", accent: "lavender", active: true },
  { id: "meal-training-snack", title: "训练前后快补", subtitle: "香蕉＋Greek yogurt，或面包＋牛奶", mealSlots: ["加餐"], source: "灵活", tags: ["训练", "应急", "免开火"], proteinHint: "约 10–20g", recipeId: "recipe-training-snack", prepNote: "常备香蕉、酸奶或牛奶", notes: "两小时内吃过正餐就不必额外吃；训练后几小时内正常吃饭即可。", accent: "lime", active: true },
];

export const defaultMealRecipes: MealRecipe[] = [
  { id: "recipe-tims-belt", title: "Tims 训练启动早餐", servings: 1, prepMinutes: 5, cookMinutes: 0, ingredients: [{ name: "Bagel B.E.L.T.", amount: "1 个", category: "蛋白质" }, { name: "香蕉或苹果", amount: "1 份", category: "蔬果" }, { name: "Medium iced coffee", amount: "1 杯，half sweet，milk", category: "调味与其他" }, { name: "Plain Greek yogurt", amount: "1 盒（当早午饭时可选）", category: "乳品与替代", optional: true }], steps: ["在 Tim Hortons 点一个 Bagel B.E.L.T.。", "咖啡选 Medium、half sweet，尽量用 milk。", "搭配一份完整水果；若作为早午饭，再加 Greek yogurt 或两个水煮蛋。"], prepAhead: ["确认家里或 Nations 有可直接带走的水果。"], notes: "不需要用 5–10 个 Timbits 补足早午饭。" },
  { id: "recipe-yogurt-oats", title: "Greek yogurt 燕麦碗", servings: 1, prepMinutes: 5, cookMinutes: 0, ingredients: [{ name: "Plain Greek yogurt", amount: "约 200g", category: "乳品与替代" }, { name: "燕麦", amount: "约半杯", category: "主食" }, { name: "香蕉或莓果", amount: "1 份", category: "蔬果" }, { name: "无盐坚果", amount: "一小把", category: "调味与其他" }], steps: ["Greek yogurt 放入碗或密封盒。", "加入燕麦和切好的水果。", "最后撒一小把坚果；想做 overnight oats 时前一晚冷藏。"], prepAhead: ["将燕麦和坚果分装成一周小份。", "莓果洗净并彻底沥干。"], notes: "普通早餐不需要同时大量加入 granola、蜂蜜和花生酱。" },
  { id: "recipe-chinese-breakfast", title: "中式温热早餐", servings: 1, prepMinutes: 5, cookMinutes: 8, ingredients: [{ name: "鸡蛋", amount: "2 个", category: "蛋白质" }, { name: "无糖豆奶或牛奶", amount: "1 杯", category: "乳品与替代" }, { name: "红薯、玉米或全麦面包", amount: "1 份", category: "主食" }, { name: "橙子、苹果或猕猴桃", amount: "1 份", category: "蔬果" }], steps: ["加热提前煮好的鸡蛋与红薯/玉米，或烤两片全麦面包。", "倒一杯无糖豆奶或牛奶。", "搭配一份完整水果。"], prepAhead: ["一次煮 6–8 个鸡蛋，冷藏分几天吃。", "蒸熟 2–3 份红薯或玉米。"], notes: "无糖豆奶优先；不要同时叠加油条和甜面包。" },
  { id: "recipe-tims-protein", title: "Tims 轻量高蛋白早餐", servings: 1, prepMinutes: 5, cookMinutes: 0, ingredients: [{ name: "Egg & Cheese English Muffin", amount: "1 个", category: "蛋白质" }, { name: "Medium Iced Protein Latte", amount: "1 杯", category: "乳品与替代" }, { name: "香蕉、苹果或橙子", amount: "1 份", category: "蔬果" }], steps: ["点 Egg & Cheese English Muffin。", "饮料选 Medium Iced Protein Latte，不额外加糖浆。", "配一份从 Nations 带来的水果。"], prepAhead: ["前一天准备一份可带走的水果。"], notes: "门店菜单变化时在 Tim Hortons App 内确认。" },
  { id: "recipe-pb-toast", title: "全麦花生酱早餐", servings: 1, prepMinutes: 5, cookMinutes: 2, ingredients: [{ name: "全麦面包", amount: "2 片", category: "主食" }, { name: "花生酱", amount: "1–2 汤匙", category: "调味与其他" }, { name: "Plain Greek yogurt", amount: "约 200g", category: "乳品与替代" }, { name: "香蕉", amount: "1 根", category: "蔬果" }], steps: ["全麦面包烤热，薄薄涂 1–2 汤匙花生酱。", "配 Greek yogurt 和香蕉。", "咖啡按上午、中杯、少糖规则处理。"], prepAhead: [], notes: "若改用整个 Bagel，减少花生酱或其他主食份量。" },
  { id: "recipe-strength-brunch", title: "力量训练早午饭", servings: 1, prepMinutes: 8, cookMinutes: 10, ingredients: [{ name: "鸡蛋", amount: "2–3 个", category: "蛋白质" }, { name: "全麦 Bagel 或面包", amount: "1 份", category: "主食" }, { name: "番茄、黄瓜或菠菜", amount: "1–2 拳", category: "蔬果" }, { name: "水果", amount: "1 份", category: "蔬果" }], steps: ["鸡蛋煎、煮或炒熟。", "加热全麦 Bagel 或面包。", "加入一到两种方便蔬菜和一份水果。"], prepAhead: ["洗好番茄、黄瓜或菠菜并分装。"], notes: "训练前吃时留出约 2–3 小时；训练后吃则正常完成整顿即可。" },
  { id: "recipe-treat-breakfast", title: "有边界的甜点早餐", servings: 1, prepMinutes: 5, cookMinutes: 0, ingredients: [{ name: "Greek yogurt 或鸡蛋", amount: "1 份", category: "蛋白质" }, { name: "水果", amount: "1 份", category: "蔬果" }, { name: "燕麦", amount: "少量，可选", category: "主食", optional: true }, { name: "Timbits", amount: "1–2 个", category: "调味与其他" }, { name: "Medium coffee", amount: "1 杯", category: "调味与其他" }], steps: ["先吃鸡蛋或酸奶，再吃水果。", "最后吃 1–2 个最喜欢的 Timbits。", "咖啡选 Medium、少糖并放在上午。"], prepAhead: [], notes: "偶尔吃多一点不是严重问题，重点是不把它变成每日标准。" },
  { id: "recipe-nations-plate", title: "Nations Food Court 选餐法", servings: 1, prepMinutes: 3, cookMinutes: 0, ingredients: [{ name: "鸡肉、鱼、牛肉或豆腐", amount: "1 掌到 1.5 掌", category: "蛋白质" }, { name: "米饭、面或土豆", amount: "约 1 拳", category: "主食" }, { name: "两种蔬菜", amount: "共 1–2 拳", category: "蔬果" }], steps: ["先选一个明确蛋白质。", "再选一拳左右主食。", "最后补齐两种蔬菜；酱汁少一点。"], prepAhead: [], notes: "可以自由换菜，不需要追求每天完全相同。" },
  { id: "recipe-chicken-rice", title: "鸡肉双蔬饭", servings: 3, prepMinutes: 15, cookMinutes: 25, ingredients: [{ name: "鸡胸或去皮鸡腿", amount: "450–500g", category: "蛋白质" }, { name: "米", amount: "约 3 杯熟饭", category: "主食" }, { name: "西兰花", amount: "1 大颗或 1 袋冷冻", category: "蔬果" }, { name: "绿叶菜", amount: "1 把", category: "蔬果" }, { name: "食用油与基础调味", amount: "适量", category: "调味与其他" }], steps: ["鸡肉切成均匀大小，少量油和调味腌 10 分钟。", "鸡肉煎或烤至完全熟透。", "西兰花与绿叶菜快速蒸或炒熟。", "和米饭分装；酱汁单独保存。"], prepAhead: ["周日先完成鸡肉和西兰花的 3 份分装。", "绿叶菜洗净沥干，吃前再炒。"], notes: "冷藏熟食按气味、状态和食品安全判断，不要机械放满整周。" },
  { id: "recipe-beef-noodles", title: "牛肉蔬菜面", servings: 2, prepMinutes: 12, cookMinutes: 15, ingredients: [{ name: "瘦牛肉片", amount: "250g", category: "蛋白质" }, { name: "鸡蛋", amount: "2 个", category: "蛋白质" }, { name: "面条", amount: "2 份", category: "主食" }, { name: "青菜", amount: "2–3 拳", category: "蔬果" }, { name: "胡萝卜或甜椒", amount: "1 份", category: "蔬果" }], steps: ["牛肉分份调味，蔬菜切好。", "煮面并在最后加入青菜。", "牛肉快速炒熟，与鸡蛋和蔬菜一起放到面上。"], prepAhead: ["牛肉按每餐份量冷藏或冷冻。", "青菜提前洗净，彻底沥干后保存。"], notes: "汤面少喝高钠汤底；炒面避免额外大量油。" },
  { id: "recipe-salmon", title: "三文鱼完整餐", servings: 2, prepMinutes: 10, cookMinutes: 18, ingredients: [{ name: "三文鱼", amount: "2 份，每份约 100–150g", category: "蛋白质" }, { name: "米饭或土豆", amount: "2 份", category: "主食" }, { name: "沙拉菜", amount: "3–4 拳", category: "蔬果" }, { name: "柠檬与基础调味", amount: "适量", category: "调味与其他" }], steps: ["三文鱼擦干，简单调味。", "烤箱或平底锅加热至中心熟透。", "搭配米饭/土豆和大份沙拉。"], prepAhead: ["冷冻鱼提前一晚放冷藏解冻。", "沙拉菜洗净并完全沥干。"], notes: "无需额外大量奶油酱。" },
  { id: "recipe-tofu", title: "豆腐炒蔬菜饭", servings: 2, prepMinutes: 12, cookMinutes: 15, ingredients: [{ name: "硬豆腐", amount: "1 大块", category: "蛋白质" }, { name: "毛豆或鸡蛋", amount: "1 份，可选", category: "蛋白质", optional: true }, { name: "混合蔬菜", amount: "4 拳", category: "蔬果" }, { name: "米饭", amount: "2 份", category: "主食" }, { name: "蒜、酱油与食用油", amount: "少量", category: "调味与其他" }], steps: ["豆腐压干水分后切块。", "豆腐先煎至表面定型，盛出。", "蔬菜快炒，再把豆腐放回并少量调味。", "搭配米饭；需要时加毛豆或鸡蛋。"], prepAhead: ["周日洗切耐储存蔬菜。", "豆腐在烹饪当天再开封沥水。"], notes: "冷冻混合蔬菜也完全可用。" },
  { id: "recipe-tomato-egg", title: "番茄炒蛋套餐", servings: 2, prepMinutes: 8, cookMinutes: 12, ingredients: [{ name: "鸡蛋", amount: "4–5 个", category: "蛋白质" }, { name: "番茄", amount: "3 个", category: "蔬果" }, { name: "绿叶菜", amount: "2 拳", category: "蔬果" }, { name: "米饭", amount: "2 份", category: "主食" }], steps: ["鸡蛋打散后炒到刚凝固，先盛出。", "番茄炒软，再放回鸡蛋。", "另炒一份绿叶菜并搭配米饭。"], prepAhead: ["绿叶菜提前洗净沥干。"], notes: "调味以能吃得舒服为准，不需要为了健康做成无盐。" },
  { id: "recipe-hotpot", title: "清爽火锅", servings: 2, prepMinutes: 15, cookMinutes: 25, ingredients: [{ name: "瘦肉、鱼片、虾或豆腐", amount: "2–3 掌", category: "蛋白质" }, { name: "白菜、蘑菇、青菜等", amount: "6–8 拳", category: "蔬果" }, { name: "面条、米饭或土豆", amount: "2 份", category: "主食" }, { name: "清汤锅底与蘸料", amount: "适量", category: "调味与其他" }], steps: ["先准备蛋白质、蔬菜和适量主食。", "先煮耐熟食材，再煮肉类与绿叶菜。", "正常吃食材，少量喝汤。"], prepAhead: [], notes: "火锅是完整一餐，不需要在之前故意挨饿。" },
  { id: "recipe-training-snack", title: "训练前后快补", servings: 1, prepMinutes: 3, cookMinutes: 0, ingredients: [{ name: "香蕉", amount: "1 根", category: "蔬果" }, { name: "Plain Greek yogurt", amount: "1 盒", category: "乳品与替代" }, { name: "全麦面包＋牛奶", amount: "可作为替代", category: "主食", optional: true }], steps: ["距离上一顿已 3–4 小时时，训练前选香蕉＋酸奶。", "不想吃酸奶时，可换面包＋牛奶。", "训练后几小时内正常吃蛋白质＋碳水正餐。"], prepAhead: ["把香蕉、酸奶或牛奶放在容易看到的位置。"], notes: "两小时内刚吃过正餐时无需额外加餐。" },
];
